version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /external/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO5OOZ1D-if00-port0:/dev/ttyRFXtrx
    restart: unless-stopped
    network_mode: host
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    secrets:
      - pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    environment:
      TZ: Europe/Oslo
      WEBPASSWORD: /run/secrets/pihole
    volumes:
      - /external/pihole/pihole:/etc/pihole
      - /external/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
secrets:
  pihole:
    file: ./pihole.pw
