version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /external/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO5OOZ1D-if00-port0:/dev/ttyRFXtrx
    restart: unless-stopped
    network_mode: host
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Oslo
    ports:
      - 1880:1880/tcp
    volumes:
      - /mnt/ssd/node-red:/data
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    secrets:
      - pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    environment:
      TZ: Europe/Oslo
      WEBPASSWORD: /run/secrets/pihole
    volumes:
      - /external/pihole/pihole:/etc/pihole
      - /external/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /external/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/pi/certbot/www:/var/www/certbot
    restart: unless-stopped
  sql:
    container_name: sql
    image: jsurf/rpi-mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - /mnt/ssd/sql:/var/lib/mysql
    restart: unless-stopped

secrets:
  pihole:
    file: ./pihole.pw
